# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pr_pb2 as pr__pb2


class PublishTopicStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.publish = channel.unary_unary(
        '/PublishTopic/publish',
        request_serializer=pr__pb2.topicData.SerializeToString,
        response_deserializer=pr__pb2.Acknowledge.FromString,
        )


class PublishTopicServicer(object):
  """The greeting service definition.
  """

  def publish(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PublishTopicServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'publish': grpc.unary_unary_rpc_method_handler(
          servicer.publish,
          request_deserializer=pr__pb2.topicData.FromString,
          response_serializer=pr__pb2.Acknowledge.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PublishTopic', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
